#!/usr/bin/env python3
"""
BMRCL Station Pair Ridership Data Enhancing Script

This script processes the station pair data generated by parse.py,
to add the following fields:
- Travelled Stations: No. of stations travelled to reach destination station, excluding origin station
- Fare Slab: Fare slab for the travelled stations
- Fare: The fare for fare slab, without applying any discounts for card payment/group bookings.
- Revenue: Fare multiplied by Ridership

Input files:
- data/stationpair-hourly.parquet

Output files:
- data/stationpair-hourly-enhanced.csv.zip
- data/stationpair-hourly-enhanced.parquet
"""

import networkx as nx
import pandas as pd

from parse import save_dataframe_to_zip

lines = {
    'purple': [
        "Challaghatta",
        "Kengeri",
        "Kengeri Bus Terminal",
        "Pattanagere",
        "Jnanabharathi",
        "Rajarajeshwari Nagar",
        "Pantharapalya - Nayandahalli",
        "Mysore Road",
        "Deepanjali Nagar",
        "Attiguppe",
        "Vijayanagar",
        "Sri Balagangadharanatha Swamiji Station, Hosahalli",
        "Magadi Road",
        "Krantivira Sangolli Rayanna Railway Station",
        "Nadaprabhu Kempegowda Station, Majestic",
        "Sir M. Visvesvaraya Stn., Central College",
        "Dr. B. R. Ambedkar Station, Vidhana Soudha",
        "Cubbon Park",
        "Mahatma Gandhi Road",
        "Trinity",
        "Halasuru",
        "Indiranagar",
        "Swami Vivekananda Road",
        "Baiyappanahalli",
        "Benniganahalli",
        "Krishnarajapura",
        "Singayyanapalya",
        "Garudacharpalya",
        "Hoodi",
        "Seetharampalya",
        "Kundalahalli",
        "Nallurahalli",
        "Sri Sathya Sai Hospital",
        "Pattandur Agrahara",
        "Kadugodi Tree Park",
        "Hopefarm Channasandra",
        "Whitefield (Kadugodi)",
    ],
    'green': [
        "Madavara",
        "Chikkabidarakallu",
        "Manjunathanagara",
        "Nagasandra",
        "Dasarahalli",
        "Jalahalli",
        "Peenya Industry",
        "Peenya",
        "Goraguntepalya",
        "Yeshwantpur",
        "Sandal Soap Factory",
        "Mahalakshmi",
        "Rajajinagar",
        "Mahakavi Kuvempu Road",
        "Srirampura",
        "Mantri Square Sampige Road",
        "Nadaprabhu Kempegowda Station, Majestic",
        "Chickpete",
        "Krishna Rajendra Market",
        "National College",
        "Lalbagh",
        "South End Circle",
        "Jayanagar",
        "Rashtreeya Vidyalaya Road",
        "Banashankari",
        "Jaya Prakash Nagar",
        "Yelachenahalli",
        "Konanakunte Cross",
        "Doddakallasandra",
        "Vajarahalli",
        "Thalaghattapura",
        "Silk Institute",
    ],
    'yellow': [
        "Rashtreeya Vidyalaya Road",
        "Ragigudda",
        "Jayadeva Hospital",
        "BTM Layout",
        "Central Silk Board",
        "Bommanahalli",
        "Hongasandra",
        "Kudlu Gate",
        "Singasandra",
        "Hosa Road",
        "Beratena Agrahara",
        "Electronic City",
        "Infosys Foundation Konappana Agrahara",
        "Huskur Road",
        "Biocon Hebbagodi",
        "Delta Electronics Bommasandra",
    ]   
}

bmrcl_nx = nx.Graph()

for line in lines.values():
    for i in range(0, len(line)-1):
        bmrcl_nx.add_edge(line[i], line[i+1])


def calculate_travelled_stations(row):
    """
    Returns number travelled stations excluding origin station
    for given row in table, 
    using the Origin Station and Destination Station columns
    """
    return len(nx.shortest_path(
      bmrcl_nx,
      row['Origin Station'],
      row['Destination Station']
    )) - 1


def calculate_fare_slab(travelled_stations):
    """
    Returns fare slab as per number of travelled stations
    ref: https://english.bmrc.co.in:8282/English/uploads/news/english//fileuploads/Revised_Fare_Chart_for_webiste.pdf
    """
    if travelled_stations > 30:
        return 10
    elif travelled_stations > 25:
        return 9
    elif travelled_stations > 20:
        return 8
    elif travelled_stations > 15:
        return 7
    elif travelled_stations > 10:
        return 6
    elif travelled_stations > 8:
        return 5
    elif travelled_stations > 6:
        return 4
    elif travelled_stations > 4:
        return 3
    elif travelled_stations > 2:
        return 2
    else:
        return 1


def calculate_fare(fare_slab):
    """
    Returns fare as per fare slab
    ref: https://english.bmrc.co.in:8282/English/uploads/news/english//fileuploads/Revised_Fare_Chart_for_webiste.pdf
    """
    fares = [10, 20, 30, 40, 50, 60, 70, 80, 90, 90]
    return fares[fare_slab - 1]


def calculate_revenue(row):
    """
    Returns the revenue generated for this ridership and fare
    """
    return row['Ridership'] * row['Fare']


df = pd.read_parquet('data/stationpair-hourly.parquet')
df['Travelled Stations'] = df.apply(calculate_travelled_stations, axis=1)
df['Fare Slab'] = df['Travelled Stations'].apply(calculate_fare_slab)
df['Fare'] = df['Fare Slab'].apply(calculate_fare)
df['Revenue'] = df.apply(calculate_revenue, axis=1)

df.to_parquet('data/stationpair-hourly-enhanced.parquet')
save_dataframe_to_zip(
  df,
  'data/stationpair-hourly-enhanced.csv.zip',
  'stationpair-hourly-enhanced.csv',
)
